[package]
name = "Cryptography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256="0.9.6"
hex="0.4.3"
rand_core="0.6.3"